name: encore2_gamesheet
description: A (digital) game sheet for Bravo (Noch Mal so gut / Keer op Keer 2)

publish_to: "none" 

version: 1.1.3+10

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  assets_audio_player: ^3.1.1
  wakelock_plus: ^1.4.0
  in_app_review: ^2.0.11
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_localizations:
    sdk: flutter

flutter:
  generate: true 
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf